title: My Dummy Website
author: adityafajri
email: adityafajrimelinianto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello i'm a indonesian programmer, glad to have you here.

# social links
twitter_username: 4zkab4n # DO NOT include the @ character, or else the build will fail!
github_username:  adityafajri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
